[package]
name = "osm-pbf-parquet"
version = "0.1.0"
edition = "2021"

[dependencies]
arrow = "52.1.0"
bytes = "1.6.1"
clap = { version = "4.5.9", features = ["derive"] }
flate2 = { version = "1.0.30", features = ["zlib-ng"], default-features = false }
futures = "0.3.30"
object_store = {version = "0.10.2", features = ["aws"] }
osmpbf = "0.3.4"
parquet = { version = "52.1.0", features = ["async"] }
# rayon = "1.10.0"
sysinfo = "0.30.13"
# TODO - reduce feature set here?
tokio = { version =  "1.38.1", features = ["full"] }
tokio-util = {version = "0.7.11", features = ["full"] }
tokio-stream = {version = "0.1.15", features = ["full"] }
url = "2.5.2"
aws-config = { version = "1", features = ["behavior-version-latest", "rt-tokio"] }
aws-sdk-s3 = { version = "1", features = ["behavior-version-latest", "rt-tokio"] }
futures-core = "0.3.30"
anyhow = "1.0.86"
either = "1.13.0"

[dev-dependencies]
criterion = "0.5.1"

[lib]
name = "osm_pbf_parquet"
path = "src/lib.rs"

[[bin]]
name = "osm-pbf-parquet"
path = "src/main.rs"

[[bench]]
name = "benchmark"
harness = false
