[package]
name = "osm-pbf-parquet"
version = "0.1.0"
edition = "2021"

[dependencies]
arrow = "52.1.0"
bytes = "1.6.1"
clap = { version = "4.5.8", features = ["derive"] }
flate2 = { version = "1.0.30", features = ["zlib-ng"], default-features = false }
futures = "0.3.30"
object_store = {version = "0.10.1", features = ["aws"] }
osmpbf = "0.2.8"
parquet = { version = "52.0.0", features = ["async"] }
rayon = "1.5.0"
sysinfo = "0.30.13"
tokio = { version =  "1.38.0", features = ["rt", "rt-multi-thread"] }
url = "2.5.2"

[dev-dependencies]
criterion = "0.3"

[lib]
name = "osm_pbf_parquet"
path = "src/lib.rs"

[[bin]]
name = "osm-pbf-parquet"
path = "src/main.rs"

[[bench]]
name = "benchmark"
harness = false
