name: Build and test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Install python test dependencies
      run: cd test && pip3 install -r requirements.txt
    - name: Install osmium
      run: apt install osmium-tool
    - name: Prepare test files
      run: ./prepare.sh
    - name: Run test
      run: python3 ./validate.py
