name: Build and test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Build
      run: cargo build
    - name: Install osmium
      run: sudo apt install osmium-tool
    - name: Install python test dependencies
      working-directory: ./test
      run: pip3 install -r requirements.txt
    - name: Prepare test files
      run: ./prepare.sh
      working-directory: ./test
    - name: Run test
      working-directory: ./test
      run: python3 ./validate.py
